version: "3.9"

services:
  postgres:
    image: postgres:13.7-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./src
      dockerfile: ./backend.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
